### PR TITLE
Migrate Travis CI to Github Actions

### PR DESCRIPTION
**Pull request by louilinn**
Related to issue: https://github.com/CirclesUBI/circles-core/issues/64

### CODE REVIEW

**Comment by llunaCreixent** [comment]
I think we should make use of the variable "working-directory", and create a subdirectory in the $GITHUB_WORKSPACE to checkout both `circles-core` and `circles-docker` repos in parallel.

**Comment by llunaCreixent** [comment]
Let's use for debugging :) 
https://github.com/marketplace/actions/debugging-with-tmate
thanks @louilinn !!

**Comment by louilinn** [comment]
Actions now reach running the core tests but we get 404 from the relayer

@adzialocha found that docker-gen is having an issue with finding out the ip addresses of the created containers, so nginx-proxy doesn't know where to route the HTTP requests.

There seems to be an issue with a docker update affecting that ip-addresses are not properly added as upstream in nginx configuration
https://github.com/jwilder/docker-gen/pull/335
https://github.com/jwilder/docker-gen/pull/336

**Comment by louilinn** [comment]
The above mentioned PRs are now merged / closed. However we still get the 404

```
FAIL test/token.test.js (7.399 s)
  ● Token › should check if safe has enough funds for token to be deployed

    RequestError: Request failed @ http://relay.circles.local/api/v3/safes/predict/ with error 404

      70 |       } else {
      71 |         if (response.status >= 400) {
    > 72 |           throw new RequestError(url, response.body, response.status);
         |                 ^
      73 |         }
      74 | 
      75 |         return response.body;

      at src/utils.js:72:17
```

**Comment by adzialocha** [comment]
> The above mentioned PRs are now merged / closed. However we still get the 404
> 
> ```
> FAIL test/token.test.js (7.399 s)
>   ● Token › should check if safe has enough funds for token to be deployed
> 
>     RequestError: Request failed @ http://relay.circles.local/api/v3/safes/predict/ with error 404
> 
>       70 |       } else {
>       71 |         if (response.status >= 400) {
>     > 72 |           throw new RequestError(url, response.body, response.status);
>          |                 ^
>       73 |         }
>       74 | 
>       75 |         return response.body;
> 
>       at src/utils.js:72:17
> ```

Was there a new version released / do we use it already?

**Comment by louilinn** [comment]
Should we update the version [here](https://github.com/CirclesUBI/circles-docker/blob/74b6c22acba4c6f637082434fdbfae81de232bd2/docker-compose.yml#L53)?

Also the issue seems to remain when using a custom hostname (which i think we do [here](https://github.com/CirclesUBI/circles-docker/blob/74b6c22acba4c6f637082434fdbfae81de232bd2/docker-compose.yml#L33)) according to comments in the PRs mentioned.

**Comment by adzialocha** [comment]
> Should we update the version [here](https://github.com/CirclesUBI/circles-docker/blob/74b6c22acba4c6f637082434fdbfae81de232bd2/docker-compose.yml#L53)?

Yes, super!

**Comment by adzialocha** [comment]
I've updated `docker-gen` to `0.7.5` in `circles-docker` and removed `tmate`. Also all circles tests are passing now (locally): https://github.com/CirclesUBI/circles-core/pull/63

I think this is ready! :partying_face:

**Review by llunaCreixent — APPROVED** [review]
Let's merge! great job!

**Comment by llunaCreixent** [comment]
Tests failing. See:
https://github.com/CirclesUBI/circles-core/runs/2294779014?check_suite_focus=true

**Comment by adzialocha** [comment]
:partying_face: :partying_face: :partying_face: :partying_face: :partying_face: Woho! I changed the tests to `--runInBand`, I really think we have a race-condition bug in the relayer (started a ticket here but will add more info soon: https://github.com/CirclesUBI/safe-relay-service/issues/44). For now we keep that flag and move back to concurrently running tests when the bug was fixed.

@louilinn if you could remove that postgres line (see feedback of @llunaCreixent), I'm happy to merge it (I have the admin rights to merge it even though the Travis CI is blocking) :palm_tree:  :penguin:

**Review by adzialocha — CHANGES_REQUESTED** [review]
:partying_face: :partying_face: :partying_face: :partying_face: :partying_face:

Woho! I changed the tests to `--runInBand` and it works, I really think we have a race-condition bug in the relayer (started a ticket here but will add more info soon: https://github.com/CirclesUBI/safe-relay-service/issues/44). For now we keep that flag and move back to concurrently running tests when the bug was fixed (created an issue here: https://github.com/CirclesUBI/circles-core/issues/75).

@louilinn if you could remove that PostgreSQL part (see feedback of @llunaCreixent), I'm happy to merge it (I have the admin rights to merge it even though the Travis CI is blocking) :palm_tree:  :penguin:

**Comment by louilinn** [comment]
The PostgreSQL part is already gone :) I removed the travis file. I think we should squash all these commits when merging haha ^^

**Review by adzialocha — APPROVED** [review]

**Pull request merged**
