### PR TITLE
Add possibility in getLatest to get mutual activity by providing otherSafeAddress

### PR DESCRIPTION
**Pull request by louilinn**
Related to #53 

- [x] query tested against the graph in playground
- [x] functionality added in code
- [x] understand why response is undefined - something is wrong with the query. You can console log query in utils to see it
- [x] complete unit tests

### CODE REVIEW

**Comment by louilinn** [comment]
Example query between me and llunas account:
```
{
notifications(
orderBy: "time",
orderDirection: "desc",
first: 10, skip: 0,
where: { or:[
{
time_gt: 0,
safeAddress: "0x0b900cbbc0e6bc4edc12f56360c8bc141ed1cc1b",
type: TRUST,
trust_: {
user: "0x3cb406def33aed0abd6d02a75fedca8e2e8d1a2e",
}
},
{
time_gt: 0,
safeAddress: "0x0b900cbbc0e6bc4edc12f56360c8bc141ed1cc1b",
type: TRUST,
trust_: {
canSendTo: "0x3cb406def33aed0abd6d02a75fedca8e2e8d1a2e",
}
},
{
time_gt: 0,
safeAddress: "0x0b900cbbc0e6bc4edc12f56360c8bc141ed1cc1b",
type: TRANSFER,
transfer_: {
to: "0x3cb406def33aed0abd6d02a75fedca8e2e8d1a2e",
}
},
{
time_gt: 0,
safeAddress: "0x0b900cbbc0e6bc4edc12f56360c8bc141ed1cc1b",
type: TRANSFER,
transfer_: {
from: "0x3cb406def33aed0abd6d02a75fedca8e2e8d1a2e",
}
},
]
}
)
{
id transactionHash safeAddress type time trust
{ user canSendTo limitPercentage }
transfer
{ from to amount }
hubTransfer
{ from to amount }
ownership
{ adds removes }
}
}
```

**Comment by JacqueGM** [comment]
the issue with not being able to execute the query was the version of the graph, the related PR will fix the issue. You will have to do make subgraph to download latest version and rebuild the containers locally

**Comment by mikozet** [comment]
> the issue with not being able to execute the query was the version of the graph, the related PR will fix the issue. You will have to do make subgraph to download latest version and rebuild the containers locally

I added an issue with new version https://github.com/CirclesUBI/circles-docker/issues/87

**Comment by mikozet** [comment]
> > the issue with not being able to execute the query was the version of the graph, the related PR will fix the issue. You will have to do make subgraph to download latest version and rebuild the containers locally
> 
> I added an issue with new version [CirclesUBI/circles-docker#87](https://github.com/CirclesUBI/circles-docker/issues/87)

this issue is resolved

**Review by juanenrisley — APPROVED** [review]
👍🏿 LGTM

**Review by JacqueGM — APPROVED** [review]

**Pull request merged**
