### PR TITLE
Increase user limit trust to 100%

### LINKED ISSUE #151: Change trust limits of trusts to 100%

### PR DESCRIPTION
**Pull request by juanenrisley**
Closes #151

### CODE REVIEW

**Review by llunaCreixent — APPROVED** [review]
This looks good, although let's wait to plan the changes with product

**Comment by juanenrisley** [comment]
The PR won't be merged until we find an approach with @triaslucia to apply the new limit within myxogastria.

**Comment by louilinn** [comment]
Can you elaborate on what we need to decide?

**Comment by juanenrisley** [comment]
> 

We only need to speak with Lucia about what we already decided in #643

**Comment by juanenrisley** [comment]
Merging PR as this will only affect new trusts.

**Comment by louilinn** [comment]
We neew to redo this next sprint :)

**Pull request merged**
