### PR TITLE
Fix broken or outdated token tests

### PR DESCRIPTION
**Pull request by adzialocha**
**Todos:**

* [x] Check if `circles-core` tests pass against latest `circles-api` version 
* [x] Fix `Token > Transitive Transactions > should send Circles to someone transitively`
  Initial payout got changed in Circles contracts
* [x] Fix `Token > Transitive Transactions > should get the current balance`
  Initial payout got changed in Circles contracts
* [x] Fix `Token › Find transitive transfer steps › should return empty path when no transfer is possible`
  The new `pathfinder` executable behaves slightly different now and returns already transfer steps as soon as a max flow is given (unlike in the past where it returned an empty array). We deleted the test as it was testing a case which is not implemented anymore in the `pathfinder`. Also, we test against the expected invalid transfer in another test already.
* [x] Fix `Token › Find transitive transfer steps › should return max flow and possible path`
  The new `pathfinder` simply just comes up with a different transfer solution here. We just need to change the expected outcome.
* [x] Fix `Token › Transitive Transactions › should fail sending Circles when there is no path`
   This one is actually NOT broken! The pathfinder and the core works as expected, but the `circles-api` itself is generating wrong trust network data in the `edges.json`! In this case there is a bug somewhere in how the `edges.json` file gets build in the api. This should be fixed by refactoring the indexing algorithm in the api, see https://github.com/CirclesUBI/circles-api/pull/24

### CODE REVIEW

**Comment by llunaCreixent** [comment]
Failing tests:
Token > Find transitive transfer steps > should return max flow and possible path
Token > Transitive Transactions > should send Circles to someone transitively

Fixed: 
Token > Transitive Transactions > should get the current balance


Running tests with:
`npm run test token  --verbose=false`
and the `circles-api` in branch `logging` (commit e72ce7f23b99e382680858e1dc2fe2ef024630f6)
Time:        231.458 s

**Comment by adzialocha** [comment]
The addition with checking the initial payout looks good! :seedling: 

> Running tests with:
> npm run test token --verbose=false
> and the circles-api in branch logging (commit e72ce7f23b99e382680858e1dc2fe2ef024630f6)

Small side note: I would not recommend running against the `circles-api` `logging` branch as the implementation is not stable. For our CI we should test against everything which is in `main`.

**Comment by adzialocha** [comment]
I've added some small tweaks to the `loop` helper method to help us debugging a little better :+1:

**Comment by adzialocha** [comment]
Super, if we fix the signupBonus we are ready to go, right @llunaCreixent?

**Comment by llunaCreixent** [comment]
When I run the tests (only the `Token > Transitive Transactions > should send Circles to someone transitively` test) several times with the docker deployment, the 3rd or 4th time the test fail with this error:
```
    RequestError: Request failed @ http://relay.circles.local/api/v2/safes/0x514c97a4fa711D4f2B55354FEf4454F05C07D6b1/transactions/estimate/ with error 422

```
Therefore, I restart the docker containers and tests run well again:
```
make ENV=backend down
docker volume prune -f
make ENV=backend up 
make ENV=backend contracts
make ENV=backend subgraph
make ENV=backend up # sometimes circles-api-worker is down
```

**Comment by adzialocha** [comment]
Running the tests against the latest `circles-api` version fail @llunaCreixent. I've set this PR to draft and added the todo. Here are some logs from the `circles-api` container (added some logging there and built the docker via `make up API=build`:

```
{
  error: Error: Process failed with /usr/src/app/pathfinder 0x6214B1534C11F054f22C2a83722c126A7F9545D6 0x72c29E666B08D36655A4A71b09E0432F3Bd91D95 1 /usr/src/app/edges-data/edges.json
      at /usr/src/app/node_modules/@circles/transfer/lib/index.js:86:16
      at ChildProcess.exithandler (child_process.js:315:5)
      at ChildProcess.emit (events.js:314:20)
      at ChildProcess.EventEmitter.emit (domain.js:483:12)
      at maybeClose (internal/child_process.js:1022:16)
      at Socket.<anonymous> (internal/child_process.js:444:11)
      at Socket.emit (events.js:314:20)
      at Socket.EventEmitter.emit (domain.js:483:12)
      at Pipe.<anonymous> (net.js:675:12),
  body: {
    from: '0x6214B1534C11F054f22C2a83722c126A7F9545D6',
    to: '0x72c29E666B08D36655A4A71b09E0432F3Bd91D95',
    value: '1'
  }
}
```

**Comment by adzialocha** [comment]
Ok, I fixed this error in the Dockerfile of `circles-api` which caused the `pathfinder` service to not work: https://github.com/CirclesUBI/circles-api/commit/99db7148924c2e536ba429b9815a9196d72078af.

**Comment by adzialocha** [comment]
:partying_face: It all passes now! The `should fail sending Circles when there is no path` problem was fixed by changing another test which made the "assumingly failing" test actually pass because it redistributed tokens in a way where the account transitively would be able to send Circles anyhow :boom: 

```
 PASS  test/token.test.js (353.371 s)
  Token
    ✓ should check if safe has enough funds for token to be deployed (1694 ms)
    Payment notes
      ✓ should receive the payment note (60 ms)
      ✓ should disallow access for other users and return null (66 ms)
    Find transitive transfer steps
      ✓ should return max flow and possible path (9 ms)
    Transitive Transactions
      ✓ should get the current balance (26 ms)
      ✓ should send Circles to someone directly (13500 ms)
      ✓ should send Circles to someone transitively (16456 ms)
      ✓ should fail sending Circles when there is no path (47 ms)
      requestUBIPayout
        ✓ should add the next payout to our balance (12946 ms)
```

**Review by llunaCreixent — APPROVED** [review]
Excited to see it working :)

**Pull request merged**
